pub mod alias;
pub mod cache;
pub mod completion;
pub mod config;
pub mod current;
pub mod dispatch;
pub mod doctor;
pub mod init;
pub mod install;
pub mod list;
pub mod remove;
pub mod self_update;
pub mod switch;

pub use alias::{AliasAction, AliasArgs};
pub use cache::{CacheAction, CacheArgs};
pub use completion::CompletionArgs;
pub use config::{ConfigAction, ConfigArgs};
pub use dispatch::dispatch;
pub use init::InitArgs;
pub use install::InstallArgs;
pub use list::ListArgs;
pub use remove::RemoveArgs;
pub use self_update::SelfUpdateArgs;
pub use switch::SwitchArgs;
