# >>> jswitch init >>>
# JSwitch shell integration for Bash/Zsh
# This file is auto-generated by `jswitch init`. Do not edit manually.

# ─── jswitch wrapper function (captures session-level switch output) ──────
jswitch() {
    local cmd="${1:-}"; shift || true

    # Run the real jswitch binary
    command jswitch "$cmd" "$@"
    local exit_code=$?

    # If this was a session-level switch, eval the export output
    if [[ "$cmd" == "switch" ]]; then
        local in_session=false
        for arg in "$@"; do
            if [[ "$arg" == "--session" ]]; then
                in_session=true
                break
            fi
        done

        if $in_session; then
            # Re-run just to capture env exports, suppress other output
            eval "$(command jswitch env 2>/dev/null)"
        fi
    fi

    return $exit_code
}

# ─── Auto-load Java version on directory change (cd hook) ─────────────────
if [[ -n "${ZSH_VERSION:-}" ]]; then
    # Zsh: use chpwd hook
    __jswitch_load_project_java() {
        [[ -f .java-version ]] || return 0
        eval "$(command jswitch env 2>/dev/null)"
    }

    # Register hook only if not already registered
    if ! typeset -f chpwd_functions &>/dev/null || \
       ! [[ " ${chpwd_functions[*]} " =~ " __jswitch_load_project_java " ]]; then
        autoload -Uz add-zsh-hook 2>/dev/null
        add-zsh-hook chpwd __jswitch_load_project_java 2>/dev/null || true
    fi

    # Also run on initial shell load
    __jswitch_load_project_java

else
    # Bash: use PROMPT_COMMAND or cd wrapper
    __jswitch_prev_pwd=""

    __jswitch_check_cd() {
        local pwd="$(pwd)"
        if [[ "$pwd" != "$__jswitch_prev_pwd" ]]; then
            __jswitch_prev_pwd="$pwd"
            if [[ -f .java-version ]]; then
                eval "$(command jswitch env 2>/dev/null)"
            fi
        fi
    }

    # Append to existing PROMPT_COMMAND rather than replacing it
    if [[ -n "${PROMPT_COMMAND:-}" ]]; then
        export PROMPT_COMMAND="__jswitch_check_cd;${PROMPT_COMMAND}"
    else
        export PROMPT_COMMAND="__jswitch_check_cd"
    fi

    # Also run on initial shell load
    __jswitch_check_cd
fi

# ─── Convenience aliases ──────────────────────────────────────────────────
alias js='jswitch switch'
alias jsl='jswitch list --installed'
alias jsc='jswitch current'

# <<< jswitch init <<<
