# >>> jswitch init >>>
# JSwitch shell integration for Bash/Zsh
# This file is auto-generated by `jswitch init`. Do not edit manually.

# ─── jswitch wrapper function ─────────────────────────────────────────────
jswitch() {
    local cmd="${1:-}"; shift || true

    command jswitch "$cmd" "$@"
    local exit_code=$?

    # 切换版本后重新加载环境变量
    if [[ "$cmd" == "switch" ]]; then
        eval "$(command jswitch env 2>/dev/null)"
    fi

    return $exit_code
}

# ─── Apply global Java version on shell startup ───────────────────────────
# 每次进入新目录时重新应用全局默认版本，确保 JAVA_HOME 和 PATH 始终正确
__jswitch_apply_env() {
    eval "$(command jswitch env 2>/dev/null)"
}

if [[ -n "${ZSH_VERSION:-}" ]]; then
    # Zsh: use chpwd hook
    autoload -Uz add-zsh-hook 2>/dev/null
    add-zsh-hook chpwd __jswitch_apply_env 2>/dev/null || true
else
    # Bash: use PROMPT_COMMAND
    if [[ -n "${PROMPT_COMMAND:-}" ]]; then
        export PROMPT_COMMAND="__jswitch_apply_env;${PROMPT_COMMAND}"
    else
        export PROMPT_COMMAND="__jswitch_apply_env"
    fi
fi

# Shell 启动时立即应用
__jswitch_apply_env

# ─── Convenience aliases ──────────────────────────────────────────────────
alias js='jswitch switch'
alias jsl='jswitch list --installed'
alias jsc='jswitch current'

# <<< jswitch init <<<
