# >>> jswitch init >>>
# JSwitch shell integration for PowerShell
# This file is auto-generated by `jswitch init`. Do not edit manually.

function global:jswitch {
    $argsArr = @($args)
    $cmd = if ($argsArr.Count -gt 0) { $argsArr[0] } else { $null }
    $rest = if ($argsArr.Count -gt 1) { $argsArr[1..($argsArr.Count - 1)] } else { @() }

    & jswitch @args
    $exitCode = $LASTEXITCODE

    if ($cmd -eq 'switch' -and $rest -contains '--session') {
        $envOutput = & jswitch env 2>$null
        foreach ($line in $envOutput) {
            if ($line -match '^export\s+(\w+)=(.*)$') {
                $name = $Matches[1]
                $value = $Matches[2] -replace '"', ''
                [System.Environment]::SetEnvironmentVariable($name, $value, 'Process')
                Set-Item -Path "env:$name" -Value $value
            }
        }
    }

    $LASTEXITCODE = $exitCode
}

function global:Invoke-JSwitchAutoLoad {
    if (Test-Path '.java-version') {
        $envOutput = & jswitch env 2>$null
        foreach ($line in $envOutput) {
            if ($line -match '^export\s+(\w+)=(.*)$') {
                $name = $Matches[1]
                $value = $Matches[2] -replace '"', ''
                [System.Environment]::SetEnvironmentVariable($name, $value, 'Process')
                Set-Item -Path "env:$name" -Value $value
            }
        }
    }
}

Invoke-JSwitchAutoLoad

Set-Alias -Name js -Value 'jswitch switch' -Option AllScope -Force
New-Alias -Name jsl { jswitch list --installed } -Scope Global -Force
New-Alias -Name jsc { jswitch current } -Scope Global -Force

# <<< jswitch init <<<
