# >>> jswitch init >>>
# JSwitch shell integration for fish
# This file is auto-generated by `jswitch init`. Do not edit manually.

# ─── jswitch wrapper function (captures session-level switch output) ──────
function jswitch
    set -l cmd $argv[1]
    set -e argv[1]

    command jswitch $cmd $argv

    # Capture and eval export output from switch --session
    if test "$cmd" = "switch"
        and contains -- --session $argv
        set -l env_output (command jswitch env 2>/dev/null)
        for line in $env_output
            eval (string replace 'export ' '' $line)
        end
    end
end

# ─── Auto-detect .java-version on directory change ───────────────────────
function __jswitch_auto_load --on-variable PWD
    if test -f .java-version
        set -l env_output (command jswitch env 2>/dev/null)
        for line in $env_output
            eval (string replace 'export ' '' $line)
        end
    end
end

# Run on initial shell load
if test -f .java-version
    set -l env_output (command jswitch env 2>/dev/null)
    for line in $env_output
        eval (string replace 'export ' '' $line)
    end
end

# ─── Abbreviations (fish's version of aliases) ───────────────────────────
abbr -a js 'jswitch switch'
abbr -a jsl 'jswitch list --installed'
abbr -a jsc 'jswitch current'

# <<< jswitch init <<<
